"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.menuItems = void 0;
const sizeDetails = (tr, en, fr) => ({ tr, en, fr });
exports.menuItems = [
    {
        slug: 'espresso',
        category: 'coffee',
        name: { tr: 'Espresso', en: 'Espresso', fr: 'Espresso' },
        description: {
            tr: 'Tek shot espresso',
            en: 'Single shot espresso',
            fr: 'Espresso simple',
        },
        price: 100,
        isFeatured: true,
        sortOrder: 1,
    },
    {
        slug: 'double-espresso',
        category: 'coffee',
        name: { tr: 'Double Espresso', en: 'Double Espresso', fr: 'Double Espresso' },
        description: {
            tr: 'Çift shot espresso',
            en: 'Double shot espresso',
            fr: 'Double espresso',
        },
        price: 150,
        sortOrder: 2,
    },
    {
        slug: 'americano',
        category: 'coffee',
        name: { tr: 'Americano', en: 'Americano', fr: 'Americano' },
        description: {
            tr: 'Espresso ve sıcak su',
            en: 'Espresso with hot water',
            fr: 'Espresso et eau chaude',
        },
        details: sizeDetails('S / M / T: 150 / 160 / 170 ₺', 'S / M / L: 150 / 160 / 170 ₺', 'S / M / L : 150 / 160 / 170 ₺'),
        price: 150,
        sortOrder: 3,
    },
    {
        slug: 'cappuccino',
        category: 'coffee',
        name: { tr: 'Cappuccino', en: 'Cappuccino', fr: 'Cappuccino' },
        description: {
            tr: 'Espresso, buharla ısıtılmış süt ve köpük',
            en: 'Espresso with steamed milk and foam',
            fr: 'Espresso, lait chauffé à la vapeur et mousse',
        },
        details: sizeDetails('M / T: 170 / 190 ₺', 'M / L: 170 / 190 ₺', 'M / L : 170 / 190 ₺'),
        price: 170,
        allergens: ['milk'],
        sortOrder: 4,
    },
    {
        slug: 'latte',
        category: 'coffee',
        name: { tr: 'Latte', en: 'Latte', fr: 'Latte' },
        description: {
            tr: 'Espresso ve kremsi süt',
            en: 'Espresso with creamy steamed milk',
            fr: 'Espresso et lait crémeux',
        },
        details: sizeDetails('M / T: 170 / 190 ₺', 'M / L: 170 / 190 ₺', 'M / L : 170 / 190 ₺'),
        price: 170,
        allergens: ['milk'],
        isFeatured: true,
        sortOrder: 5,
    },
    {
        slug: 'gurme-latte',
        category: 'coffee',
        name: { tr: 'Gurme Latte', en: 'Gourmet Latte', fr: 'Latte Gourmand' },
        description: {
            tr: 'Özel harman espresso ve süt',
            en: 'Specialty blend espresso with milk',
            fr: 'Espresso de mélange spécial et lait',
        },
        price: 180,
        allergens: ['milk'],
        sortOrder: 6,
    },
    {
        slug: 'aromali-latte',
        category: 'coffee',
        name: { tr: 'Aromalı Latte', en: 'Flavored Latte', fr: 'Latte Aromatisé' },
        description: {
            tr: 'Vanilya, karamel veya fındık aromalı latte',
            en: 'Latte with vanilla, caramel or hazelnut',
            fr: 'Latte vanille, caramel ou noisette',
        },
        price: 180,
        allergens: ['milk'],
        sortOrder: 7,
    },
    {
        slug: 'mocha',
        category: 'coffee',
        name: { tr: 'Mocha', en: 'Mocha', fr: 'Mocha' },
        description: {
            tr: 'Espresso, çikolata ve süt',
            en: 'Espresso with chocolate and milk',
            fr: 'Espresso, chocolat et lait',
        },
        details: sizeDetails('M / T: 175 / 200 ₺', 'M / L: 175 / 200 ₺', 'M / L : 175 / 200 ₺'),
        price: 175,
        allergens: ['milk'],
        sortOrder: 8,
    },
    {
        slug: 'white-mocha',
        category: 'coffee',
        name: { tr: 'White Mocha', en: 'White Mocha', fr: 'White Mocha' },
        description: {
            tr: 'Espresso, beyaz çikolata ve süt',
            en: 'Espresso with white chocolate and milk',
            fr: 'Espresso, chocolat blanc et lait',
        },
        details: sizeDetails('M / T: 175 / 200 ₺', 'M / L: 175 / 200 ₺', 'M / L : 175 / 200 ₺'),
        price: 175,
        allergens: ['milk'],
        sortOrder: 9,
    },
    {
        slug: 'flat-white',
        category: 'coffee',
        name: { tr: 'Flat White', en: 'Flat White', fr: 'Flat White' },
        description: {
            tr: 'Çift ristretto ve ince süt köpüğü',
            en: 'Double ristretto with microfoam',
            fr: 'Double ristretto et micro-mousse',
        },
        details: sizeDetails('M / T: 160 / 180 ₺', 'M / L: 160 / 180 ₺', 'M / L : 160 / 180 ₺'),
        price: 160,
        allergens: ['milk'],
        sortOrder: 10,
    },
    {
        slug: 'cortado',
        category: 'coffee',
        name: { tr: 'Cortado', en: 'Cortado', fr: 'Cortado' },
        description: {
            tr: 'Espresso ve eşit oranda ısıtılmış süt',
            en: 'Espresso cut with equal parts warm milk',
            fr: 'Espresso coupé avec du lait tiède',
        },
        price: 160,
        allergens: ['milk'],
        sortOrder: 11,
    },
    {
        slug: 'filtre-kahve',
        category: 'coffee',
        name: { tr: 'Filtre Kahve', en: 'Filter Coffee', fr: 'Café Filtre' },
        description: {
            tr: 'Günlük demlenen filtre kahve',
            en: 'Freshly brewed filter coffee',
            fr: 'Café filtre fraîchement infusé',
        },
        price: 175,
        sortOrder: 12,
    },
    {
        slug: 'ozel-seri-filtre-kahve',
        category: 'coffee',
        name: { tr: 'Özel Seri Filtre Kahve', en: 'Specialty Filter Coffee', fr: 'Café Filtre de Spécialité' },
        description: {
            tr: 'Seçkin tek köken çekirdeklerden demleme',
            en: 'Single-origin specialty brew',
            fr: 'Infusion de grains single origin',
        },
        price: 200,
        sortOrder: 13,
    },
    {
        slug: 'turk-kahvesi',
        category: 'coffee',
        name: { tr: 'Türk Kahvesi', en: 'Turkish Coffee', fr: 'Café Turc' },
        description: {
            tr: 'Geleneksel cezvede Türk kahvesi',
            en: 'Traditional Turkish coffee',
            fr: 'Café turc traditionnel',
        },
        price: 150,
        sortOrder: 14,
    },
    {
        slug: 'sutlu-turk-kahvesi',
        category: 'coffee',
        name: { tr: 'Sütlü Türk Kahvesi', en: 'Turkish Coffee with Milk', fr: 'Café Turc au Lait' },
        description: {
            tr: 'Sütle hazırlanan Türk kahvesi',
            en: 'Turkish coffee prepared with milk',
            fr: 'Café turc préparé au lait',
        },
        price: 175,
        allergens: ['milk'],
        sortOrder: 15,
    },
    {
        slug: 'portakalli-turk-kahvesi',
        category: 'coffee',
        name: { tr: 'Portakallı Türk Kahvesi', en: 'Orange Turkish Coffee', fr: 'Café Turc à l\'Orange' },
        description: {
            tr: 'Portakal aromalı Türk kahvesi',
            en: 'Turkish coffee with orange aroma',
            fr: 'Café turc à l\'orange',
        },
        price: 175,
        sortOrder: 16,
    },
    {
        slug: 'cilekli-turk-kahvesi',
        category: 'coffee',
        name: { tr: 'Çilekli Türk Kahvesi', en: 'Strawberry Turkish Coffee', fr: 'Café Turc à la Fraise' },
        description: {
            tr: 'Çilek aromalı Türk kahvesi',
            en: 'Turkish coffee with strawberry aroma',
            fr: 'Café turc à la fraise',
        },
        price: 175,
        sortOrder: 17,
    },
    {
        slug: 'naneli-turk-kahvesi',
        category: 'coffee',
        name: { tr: 'Naneli Türk Kahvesi', en: 'Mint Turkish Coffee', fr: 'Café Turc à la Menthe' },
        description: {
            tr: 'Nane aromalı Türk kahvesi',
            en: 'Turkish coffee with mint aroma',
            fr: 'Café turc à la menthe',
        },
        price: 175,
        sortOrder: 18,
    },
    {
        slug: 'ice-americano',
        category: 'cold',
        name: { tr: 'Ice Americano', en: 'Iced Americano', fr: 'Americano Glacé' },
        description: {
            tr: 'Buzlu americano',
            en: 'Iced americano',
            fr: 'Americano glacé',
        },
        price: 175,
        sortOrder: 20,
    },
    {
        slug: 'ice-latte',
        category: 'cold',
        name: { tr: 'Ice Latte', en: 'Iced Latte', fr: 'Latte Glacé' },
        description: {
            tr: 'Buzlu latte',
            en: 'Iced latte',
            fr: 'Latte glacé',
        },
        price: 180,
        allergens: ['milk'],
        isFeatured: true,
        sortOrder: 21,
    },
    {
        slug: 'ice-gurme-latte',
        category: 'cold',
        name: { tr: 'Ice Gurme Latte', en: 'Iced Gourmet Latte', fr: 'Latte Gourmand Glacé' },
        description: {
            tr: 'Vanilya, karamel veya fındık aromalı buzlu latte',
            en: 'Iced latte with vanilla, caramel or hazelnut',
            fr: 'Latte glacé vanille, caramel ou noisette',
        },
        price: 190,
        allergens: ['milk'],
        sortOrder: 22,
    },
    {
        slug: 'ice-mocha',
        category: 'cold',
        name: { tr: 'Ice Mocha', en: 'Iced Mocha', fr: 'Mocha Glacé' },
        description: {
            tr: 'Buzlu mocha',
            en: 'Iced mocha',
            fr: 'Mocha glacé',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 23,
    },
    {
        slug: 'ice-white-mocha',
        category: 'cold',
        name: { tr: 'Ice White Mocha', en: 'Iced White Mocha', fr: 'White Mocha Glacé' },
        description: {
            tr: 'Buzlu white mocha',
            en: 'Iced white mocha',
            fr: 'White mocha glacé',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 24,
    },
    {
        slug: 'frappe',
        category: 'cold',
        name: { tr: 'Frappe', en: 'Frappe', fr: 'Frappé' },
        description: {
            tr: 'Lotus, çilek veya çikolata aromalı frappe',
            en: 'Frappe with lotus, strawberry or chocolate',
            fr: 'Frappé lotus, fraise ou chocolat',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 25,
    },
    {
        slug: 'marcher-special-latte',
        category: 'cold',
        name: { tr: 'Marcher Special Latte', en: 'Marcher Special Latte', fr: 'Latte Spécial Marcher' },
        description: {
            tr: 'Mango-passion veya çilek aromalı özel latte',
            en: 'Special latte with mango-passion or strawberry',
            fr: 'Latte spécial mangue-passion ou fraise',
        },
        price: 200,
        allergens: ['milk'],
        isFeatured: true,
        sortOrder: 26,
    },
    {
        slug: 'affogato',
        category: 'cold',
        name: { tr: 'Affogato', en: 'Affogato', fr: 'Affogato' },
        description: {
            tr: 'Espresso ve dondurma',
            en: 'Espresso poured over ice cream',
            fr: 'Espresso sur glace',
        },
        price: 175,
        allergens: ['milk'],
        sortOrder: 27,
    },
    {
        slug: 'matcha-tea',
        category: 'cold',
        name: { tr: 'Matcha Tea', en: 'Matcha Tea', fr: 'Thé Matcha' },
        description: {
            tr: 'Geleneksel matcha çayı',
            en: 'Traditional matcha tea',
            fr: 'Thé matcha traditionnel',
        },
        price: 175,
        sortOrder: 30,
    },
    {
        slug: 'cilek-matcha-tea',
        category: 'cold',
        name: { tr: 'Çilek Matcha Tea', en: 'Strawberry Matcha Tea', fr: 'Thé Matcha Fraise' },
        description: {
            tr: 'Çilek aromalı matcha',
            en: 'Strawberry matcha tea',
            fr: 'Thé matcha à la fraise',
        },
        price: 175,
        sortOrder: 31,
    },
    {
        slug: 'ice-matcha-latte',
        category: 'cold',
        name: { tr: 'Ice Matcha Latte', en: 'Iced Matcha Latte', fr: 'Matcha Latte Glacé' },
        description: {
            tr: 'Buzlu matcha latte',
            en: 'Iced matcha latte',
            fr: 'Matcha latte glacé',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 32,
    },
    {
        slug: 'ice-matcha-latte-cilek',
        category: 'cold',
        name: { tr: 'Ice Matcha Latte Çilek', en: 'Iced Strawberry Matcha Latte', fr: 'Matcha Latte Glacé Fraise' },
        description: {
            tr: 'Çilekli buzlu matcha latte',
            en: 'Iced matcha latte with strawberry',
            fr: 'Matcha latte glacé à la fraise',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 33,
    },
    {
        slug: 'ice-matcha-latte-mango',
        category: 'cold',
        name: { tr: 'Ice Matcha Latte Mango', en: 'Iced Mango Matcha Latte', fr: 'Matcha Latte Glacé Mangue' },
        description: {
            tr: 'Mangolu buzlu matcha latte',
            en: 'Iced matcha latte with mango',
            fr: 'Matcha latte glacé à la mangue',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 34,
    },
    {
        slug: 'matcha-limonata',
        category: 'cold',
        name: { tr: 'Matcha Limonata', en: 'Matcha Lemonade', fr: 'Limonade Matcha' },
        description: {
            tr: 'Matcha ve limonata',
            en: 'Matcha lemonade',
            fr: 'Limonade au matcha',
        },
        price: 200,
        sortOrder: 35,
    },
    {
        slug: 'matcha-cilekli',
        category: 'cold',
        name: { tr: 'Matcha Çilekli', en: 'Strawberry Matcha', fr: 'Matcha Fraise' },
        description: {
            tr: 'Çilekli matcha içecek',
            en: 'Strawberry matcha drink',
            fr: 'Boisson matcha fraise',
        },
        price: 190,
        sortOrder: 36,
    },
    {
        slug: 'matcha-mango-passion',
        category: 'cold',
        name: { tr: 'Matcha Mango Passion', en: 'Matcha Mango Passion', fr: 'Matcha Mangue Passion' },
        description: {
            tr: 'Mango ve passion aromalı matcha',
            en: 'Matcha with mango and passion fruit',
            fr: 'Matcha mangue et fruit de la passion',
        },
        price: 190,
        sortOrder: 37,
    },
    {
        slug: 'geleneksel-turk-cayi',
        category: 'coffee',
        name: { tr: 'Geleneksel Türk Çayı', en: 'Traditional Turkish Tea', fr: 'Thé Turc Traditionnel' },
        description: {
            tr: 'Demlikte Türk çayı',
            en: 'Turkish tea brewed in a teapot',
            fr: 'Thé turc infusé en théière',
        },
        price: 50,
        sortOrder: 40,
    },
    {
        slug: 'bitki-cayi',
        category: 'coffee',
        name: { tr: 'Bitki Çayı Çeşitleri', en: 'Herbal Teas', fr: 'Tisanes' },
        description: {
            tr: 'Günün bitki çayı seçenekleri',
            en: 'Selection of herbal teas',
            fr: 'Assortiment de tisanes',
        },
        price: 75,
        sortOrder: 41,
    },
    {
        slug: 'earl-grey-cayi',
        category: 'coffee',
        name: { tr: 'Earl Grey Çayı', en: 'Earl Grey Tea', fr: 'Thé Earl Grey' },
        description: {
            tr: 'Bergamot aromalı siyah çay',
            en: 'Black tea with bergamot',
            fr: 'Thé noir à la bergamote',
        },
        price: 75,
        sortOrder: 42,
    },
    {
        slug: 'sicak-cikolata',
        category: 'coffee',
        name: { tr: 'Sıcak Çikolata', en: 'Hot Chocolate', fr: 'Chocolat Chaud' },
        description: {
            tr: 'Kremsi sıcak çikolata',
            en: 'Creamy hot chocolate',
            fr: 'Chocolat chaud crémeux',
        },
        price: 175,
        allergens: ['milk'],
        sortOrder: 43,
    },
    {
        slug: 'sahlep',
        category: 'coffee',
        name: { tr: 'Sahlep', en: 'Sahlep', fr: 'Sahlep' },
        description: {
            tr: 'Geleneksel tarçınlı sahlep',
            en: 'Traditional cinnamon sahlep',
            fr: 'Sahlep traditionnel à la cannelle',
        },
        price: 175,
        allergens: ['milk'],
        sortOrder: 44,
    },
    {
        slug: 'chai-tea-latte',
        category: 'coffee',
        name: { tr: 'Chai Tea Latte', en: 'Chai Tea Latte', fr: 'Chaï Latte' },
        description: {
            tr: 'Baharatlı çay ve süt',
            en: 'Spiced tea with steamed milk',
            fr: 'Thé épicé et lait chauffé',
        },
        price: 175,
        allergens: ['milk'],
        sortOrder: 45,
    },
    {
        slug: 'muzlu-sut',
        category: 'cold',
        name: { tr: 'Muzlu Süt', en: 'Banana Milk', fr: 'Lait à la Banane' },
        description: {
            tr: 'Taze muzlu süt',
            en: 'Fresh banana milk',
            fr: 'Lait à la banane fraîche',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 50,
    },
    {
        slug: 'cilekli-sut',
        category: 'cold',
        name: { tr: 'Çilekli Süt', en: 'Strawberry Milk', fr: 'Lait à la Fraise' },
        description: {
            tr: 'Çilek aromalı süt',
            en: 'Strawberry flavored milk',
            fr: 'Lait aromatisé à la fraise',
        },
        price: 200,
        allergens: ['milk'],
        sortOrder: 51,
    },
    {
        slug: 'limonata',
        category: 'cold',
        name: { tr: 'Limonata', en: 'Lemonade', fr: 'Limonade' },
        description: {
            tr: 'Taze sıkım limonata',
            en: 'Fresh lemonade',
            fr: 'Limonade fraîche',
        },
        price: 175,
        sortOrder: 52,
    },
    {
        slug: 'cilekli-limonata',
        category: 'cold',
        name: { tr: 'Çilekli Limonata', en: 'Strawberry Lemonade', fr: 'Limonade à la Fraise' },
        description: {
            tr: 'Çilek ve limonata',
            en: 'Strawberry lemonade',
            fr: 'Limonade à la fraise',
        },
        price: 200,
        sortOrder: 53,
    },
    {
        slug: 'mango-passion-limonata',
        category: 'cold',
        name: { tr: 'Mango-Passion Limonata', en: 'Mango Passion Lemonade', fr: 'Limonade Mangue Passion' },
        description: {
            tr: 'Mango ve passion meyveli limonata',
            en: 'Mango and passion fruit lemonade',
            fr: 'Limonade mangue et fruit de la passion',
        },
        price: 200,
        sortOrder: 54,
    },
    {
        slug: 'naneli-limonata',
        category: 'cold',
        name: { tr: 'Naneli Limonata', en: 'Mint Lemonade', fr: 'Limonade à la Menthe' },
        description: {
            tr: 'Taze naneli limonata',
            en: 'Fresh mint lemonade',
            fr: 'Limonade à la menthe fraîche',
        },
        price: 200,
        sortOrder: 55,
    },
    {
        slug: 'frozen-sari',
        category: 'cold',
        name: { tr: 'Frozen Sarı', en: 'Frozen Yellow', fr: 'Frozen Jaune' },
        description: {
            tr: 'Tropikal sarı meyve frozen',
            en: 'Tropical yellow fruit frozen drink',
            fr: 'Boisson frozen aux fruits jaunes',
        },
        price: 200,
        sortOrder: 56,
    },
    {
        slug: 'frozen-turuncu',
        category: 'cold',
        name: { tr: 'Frozen Turuncu', en: 'Frozen Orange', fr: 'Frozen Orange' },
        description: {
            tr: 'Turunçgil frozen',
            en: 'Citrus frozen drink',
            fr: 'Boisson frozen aux agrumes',
        },
        price: 200,
        sortOrder: 57,
    },
    {
        slug: 'frozen-kirmizi',
        category: 'cold',
        name: { tr: 'Frozen Kırmızı', en: 'Frozen Red', fr: 'Frozen Rouge' },
        description: {
            tr: 'Kırmızı meyve frozen',
            en: 'Red fruit frozen drink',
            fr: 'Boisson frozen aux fruits rouges',
        },
        price: 200,
        sortOrder: 58,
    },
    {
        slug: 'frozen-yesil',
        category: 'cold',
        name: { tr: 'Frozen Yeşil', en: 'Frozen Green', fr: 'Frozen Vert' },
        description: {
            tr: 'Yeşil meyve frozen',
            en: 'Green fruit frozen drink',
            fr: 'Boisson frozen aux fruits verts',
        },
        price: 200,
        sortOrder: 59,
    },
    {
        slug: 'uludag-premium-su',
        category: 'cold',
        name: { tr: 'Uludağ Premium Su', en: 'Uludağ Premium Water', fr: 'Eau Uludağ Premium' },
        description: {
            tr: 'Şişe su',
            en: 'Bottled water',
            fr: 'Eau en bouteille',
        },
        price: 30,
        sortOrder: 60,
    },
    {
        slug: 'uludag-premium-soda',
        category: 'cold',
        name: { tr: 'Uludağ Premium Soda', en: 'Uludağ Premium Soda', fr: 'Soda Uludağ Premium' },
        description: {
            tr: 'Maden sodası',
            en: 'Sparkling mineral water',
            fr: 'Eau minérale gazeuse',
        },
        price: 60,
        sortOrder: 61,
    },
    {
        slug: 'schweppes',
        category: 'cold',
        name: { tr: 'Schweppes', en: 'Schweppes', fr: 'Schweppes' },
        description: {
            tr: 'Schweppes maden suyu',
            en: 'Schweppes tonic water',
            fr: 'Schweppes tonic',
        },
        price: 150,
        sortOrder: 62,
    },
    {
        slug: 'sade-kruvasan',
        category: 'croissant',
        name: { tr: 'Sade Kruvasan', en: 'Plain Croissant', fr: 'Croissant Nature' },
        description: {
            tr: 'Tereyağlı sade kruvasan — sadece sabah servisi',
            en: 'Butter croissant — morning service only',
            fr: 'Croissant au beurre — service matinal uniquement',
        },
        price: 150,
        allergens: ['gluten', 'milk', 'eggs'],
        isFeatured: true,
        sortOrder: 70,
    },
    {
        slug: 'cikolatali-kruvasan',
        category: 'croissant',
        name: { tr: 'Çikolatalı Kruvasan', en: 'Chocolate Croissant', fr: 'Croissant au Chocolat' },
        description: {
            tr: 'Çikolata dolgulu kruvasan — sadece sabah servisi',
            en: 'Chocolate filled croissant — morning service only',
            fr: 'Croissant fourré au chocolat — service matinal uniquement',
        },
        price: 170,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 71,
    },
    {
        slug: 'japon-coregi',
        category: 'croissant',
        name: { tr: 'Japon Çöreği', en: 'Japanese Pastry', fr: 'Viennoiserie Japonaise' },
        description: {
            tr: 'Japon usulü çörek — sadece sabah servisi',
            en: 'Japanese style pastry — morning service only',
            fr: 'Pâtisserie japonaise — service matinal uniquement',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 72,
    },
    {
        slug: 'portakalli-gronala',
        category: 'croissant',
        name: { tr: 'Portakallı Gronala', en: 'Orange Granola', fr: 'Granola à l\'Orange' },
        description: {
            tr: 'Portakallı granola — sadece sabah servisi',
            en: 'Orange granola — morning service only',
            fr: 'Granola à l\'orange — service matinal uniquement',
        },
        price: 170,
        allergens: ['gluten', 'nuts'],
        sortOrder: 73,
    },
    {
        slug: 'cilekli-granola',
        category: 'croissant',
        name: { tr: 'Çilekli Granola', en: 'Strawberry Granola', fr: 'Granola à la Fraise' },
        description: {
            tr: 'Çilekli granola — sadece sabah servisi',
            en: 'Strawberry granola — morning service only',
            fr: 'Granola à la fraise — service matinal uniquement',
        },
        price: 170,
        allergens: ['gluten', 'nuts'],
        sortOrder: 74,
    },
    {
        slug: 'tatli-sandwich',
        category: 'pastry',
        name: { tr: 'Tatlı Sandwich', en: 'Sweet Sandwich', fr: 'Sandwich Sucré' },
        description: {
            tr: 'Tatlı kruvasan sandwich',
            en: 'Sweet croissant sandwich',
            fr: 'Sandwich sucré au croissant',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 80,
    },
    {
        slug: 'profiterol',
        category: 'pastry',
        name: { tr: 'Profiterol', en: 'Profiterole', fr: 'Profiterole' },
        description: {
            tr: 'Çikolata soslu profiterol',
            en: 'Profiterole with chocolate sauce',
            fr: 'Profiterole au chocolat',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 81,
    },
    {
        slug: 'paris-prest',
        category: 'pastry',
        name: { tr: 'Paris Prest', en: 'Paris Prest', fr: 'Paris Prest' },
        description: {
            tr: 'Özel Paris prest tatlısı',
            en: 'Signature Paris prestige pastry',
            fr: 'Pâtisserie prestige Paris',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 82,
    },
    {
        slug: 'milfoy-citiri',
        category: 'pastry',
        name: { tr: 'Milföy Çıtırı', en: 'Puff Pastry Crisp', fr: 'Feuilleté Croustillant' },
        description: {
            tr: 'Çıtır milföy hamur işi',
            en: 'Crispy puff pastry',
            fr: 'Feuilleté croustillant',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 83,
    },
    {
        slug: 'brownie-pastry',
        category: 'pastry',
        name: { tr: 'Brownie', en: 'Brownie', fr: 'Brownie' },
        description: {
            tr: 'Çikolatalı brownie',
            en: 'Chocolate brownie',
            fr: 'Brownie au chocolat',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 84,
    },
    {
        slug: 'kruvasan-sandwich',
        category: 'food',
        name: { tr: 'Kruvasan Sandwich', en: 'Croissant Sandwich', fr: 'Sandwich Croissant' },
        description: {
            tr: 'Tuzlu kruvasan sandwich',
            en: 'Savory croissant sandwich',
            fr: 'Sandwich salé au croissant',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 90,
    },
    {
        slug: 'uc-peynirli',
        category: 'food',
        name: { tr: 'Üç Peynirli', en: 'Three Cheese', fr: 'Trois Fromages' },
        description: {
            tr: 'Üç peynirli kruvasan sandwich',
            en: 'Three cheese croissant sandwich',
            fr: 'Sandwich croissant aux trois fromages',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 91,
    },
    {
        slug: 'hindi-fumeli',
        category: 'food',
        name: { tr: 'Hindi Fümeli', en: 'Smoked Turkey', fr: 'Dinde Fumée' },
        description: {
            tr: 'Hindi fümeli kruvasan sandwich',
            en: 'Smoked turkey croissant sandwich',
            fr: 'Sandwich croissant à la dinde fumée',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 92,
    },
    {
        slug: 'jambonlu',
        category: 'food',
        name: { tr: 'Jambonlu', en: 'Ham', fr: 'Jambon' },
        description: {
            tr: 'Jambonlu kruvasan sandwich',
            en: 'Ham croissant sandwich',
            fr: 'Sandwich croissant au jambon',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 93,
    },
    {
        slug: 'mozzarella-domates',
        category: 'food',
        name: { tr: 'Mozzarella Domates', en: 'Mozzarella Tomato', fr: 'Mozzarella Tomate' },
        description: {
            tr: 'Mozzarella ve domatesli sandwich',
            en: 'Mozzarella and tomato sandwich',
            fr: 'Sandwich mozzarella et tomate',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 94,
    },
    {
        slug: 'somonlu',
        category: 'food',
        name: { tr: 'Somonlu', en: 'Salmon', fr: 'Saumon' },
        description: {
            tr: 'Somonlu kruvasan sandwich',
            en: 'Salmon croissant sandwich',
            fr: 'Sandwich croissant au saumon',
        },
        price: 300,
        allergens: ['gluten', 'milk', 'eggs', 'fish'],
        sortOrder: 95,
    },
    {
        slug: 'dana-kaburgali',
        category: 'food',
        name: { tr: 'Dana Kaburgalı', en: 'Beef Rib', fr: 'Côtes de Bœuf' },
        description: {
            tr: 'Dana kaburga etli sandwich',
            en: 'Beef rib croissant sandwich',
            fr: 'Sandwich aux côtes de bœuf',
        },
        price: 300,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 96,
    },
    {
        slug: 'izgara-hellim',
        category: 'food',
        name: { tr: 'Izgara Hellim', en: 'Grilled Halloumi', fr: 'Halloumi Grillé' },
        description: {
            tr: 'Izgara hellimli sandwich',
            en: 'Grilled halloumi sandwich',
            fr: 'Sandwich au halloumi grillé',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 97,
    },
    {
        slug: 'avokado-yumurta',
        category: 'food',
        name: { tr: 'Avokado-Yumurta', en: 'Avocado & Egg', fr: 'Avocat & Œuf' },
        description: {
            tr: 'Avokado ve yumurtalı sandwich',
            en: 'Avocado and egg sandwich',
            fr: 'Sandwich avocat et œuf',
        },
        price: 250,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 98,
    },
    {
        slug: 'matcha-tiramisu',
        category: 'pastry',
        name: { tr: 'Matcha Tiramisu', en: 'Matcha Tiramisu', fr: 'Tiramisu Matcha' },
        description: {
            tr: 'Matcha aromalı tiramisu',
            en: 'Matcha flavored tiramisu',
            fr: 'Tiramisu au matcha',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 100,
    },
    {
        slug: 'strawberry-matcha-cloud',
        category: 'pastry',
        name: { tr: 'Strawberry Matcha Cloud', en: 'Strawberry Matcha Cloud', fr: 'Nuage Matcha Fraise' },
        description: {
            tr: 'Çilekli matcha bulut tatlısı',
            en: 'Strawberry matcha cloud dessert',
            fr: 'Dessert nuage matcha fraise',
        },
        price: 200,
        allergens: ['milk', 'eggs'],
        sortOrder: 101,
    },
    {
        slug: 'mango-matcha-cloud',
        category: 'pastry',
        name: { tr: 'Mango Matcha Cloud', en: 'Mango Matcha Cloud', fr: 'Nuage Matcha Mangue' },
        description: {
            tr: 'Mangolu matcha bulut tatlısı',
            en: 'Mango matcha cloud dessert',
            fr: 'Dessert nuage matcha mangue',
        },
        price: 200,
        allergens: ['milk', 'eggs'],
        sortOrder: 102,
    },
    {
        slug: 'limonlu-new-york-cheesecake',
        category: 'pastry',
        name: { tr: 'Limonlu New York Cheesecake', en: 'Lemon New York Cheesecake', fr: 'Cheesecake New York Citron' },
        description: {
            tr: 'Limonlu New York usulü cheesecake',
            en: 'Lemon New York style cheesecake',
            fr: 'Cheesecake style New York au citron',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 110,
    },
    {
        slug: 'frambuazli-new-york-cheesecake',
        category: 'pastry',
        name: { tr: 'Frambuazlı New York Cheesecake', en: 'Raspberry New York Cheesecake', fr: 'Cheesecake New York Framboise' },
        description: {
            tr: 'Frambuazlı New York usulü cheesecake',
            en: 'Raspberry New York style cheesecake',
            fr: 'Cheesecake style New York à la framboise',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 111,
    },
    {
        slug: 'cikolatali-new-york-cheesecake',
        category: 'pastry',
        name: { tr: 'Çikolatalı New York Cheesecake', en: 'Chocolate New York Cheesecake', fr: 'Cheesecake New York Chocolat' },
        description: {
            tr: 'Çikolatalı New York usulü cheesecake',
            en: 'Chocolate New York style cheesecake',
            fr: 'Cheesecake style New York au chocolat',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 112,
    },
    {
        slug: 'merenga',
        category: 'pastry',
        name: { tr: 'Merenga', en: 'Meringue', fr: 'Meringue' },
        description: {
            tr: 'Özel merenga tatlısı',
            en: 'Signature meringue dessert',
            fr: 'Dessert meringue signature',
        },
        price: 200,
        allergens: ['eggs'],
        sortOrder: 113,
    },
    {
        slug: 'brownie-touch',
        category: 'pastry',
        name: { tr: 'Brownie', en: 'Brownie', fr: 'Brownie' },
        description: {
            tr: 'Marcher Touch brownie',
            en: 'Marcher Touch brownie',
            fr: 'Brownie Marcher Touch',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 114,
    },
    {
        slug: 'blondy',
        category: 'pastry',
        name: { tr: 'Blondy', en: 'Blondie', fr: 'Blondie' },
        description: {
            tr: 'Karamel ve beyaz çikolatalı blondy',
            en: 'Caramel and white chocolate blondie',
            fr: 'Blondie caramel et chocolat blanc',
        },
        price: 200,
        allergens: ['gluten', 'milk', 'eggs'],
        sortOrder: 115,
    },
];
//# sourceMappingURL=menu-data.js.map